"""OBJ/STL export helpers for software 3D models."""

from __future__ import annotations

from pathlib import Path

from gummysnake.drawing.renderer3d import Model3D

from .math3d import triangle_normal


def save_obj(model: Model3D, path: str | Path) -> Path:
    output = Path(path)
    vertex_offset = 1
    with output.open("w", encoding="utf-8") as stream:
        stream.write("# Generated by Gummy Snake\n")
        for mesh in model.meshes:
            for vertex in mesh.vertices:
                stream.write(f"v {vertex.x:.9g} {vertex.y:.9g} {vertex.z:.9g}\n")
            for u, v in mesh.texcoords:
                stream.write(f"vt {u:.9g} {v:.9g}\n")
            for face in mesh.faces:
                stream.write("f ")
                stream.write(" ".join(str(index + vertex_offset) for index in face))
                stream.write("\n")
            vertex_offset += len(mesh.vertices)
    return output


def save_stl(model: Model3D, path: str | Path, *, name: str = "gummy_snake_model") -> Path:
    output = Path(path)
    with output.open("w", encoding="utf-8") as stream:
        stream.write(f"solid {name}\n")
        for mesh in model.meshes:
            for face in mesh.faces:
                if len(face) < 3:
                    continue
                first = face[0]
                for index in range(1, len(face) - 1):
                    a, b, c = (
                        mesh.vertices[first],
                        mesh.vertices[face[index]],
                        mesh.vertices[face[index + 1]],
                    )
                    normal = triangle_normal(a, b, c)
                    stream.write(f"  facet normal {normal.x:.9g} {normal.y:.9g} {normal.z:.9g}\n")
                    stream.write("    outer loop\n")
                    for vertex in (a, b, c):
                        stream.write(f"      vertex {vertex.x:.9g} {vertex.y:.9g} {vertex.z:.9g}\n")
                    stream.write("    endloop\n")
                    stream.write("  endfacet\n")
        stream.write(f"endsolid {name}\n")
    return output
