"""OBJ/STL export helpers for software 3D models."""

from __future__ import annotations

from pathlib import Path

from gummysnake.drawing.renderer3d import Model3D

from .math3d import triangle_normal


def save_obj(model: Model3D, path: str | Path) -> Path:
    output = Path(path)
    lines: list[str] = ["# Generated by Gummy Snake"]
    vertex_offset = 1
    for mesh in model.meshes:
        for vertex in mesh.vertices:
            lines.append(f"v {vertex.x:.9g} {vertex.y:.9g} {vertex.z:.9g}")
        for u, v in mesh.texcoords:
            lines.append(f"vt {u:.9g} {v:.9g}")
        for face in mesh.faces:
            lines.append("f " + " ".join(str(index + vertex_offset) for index in face))
        vertex_offset += len(mesh.vertices)
    output.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return output


def save_stl(model: Model3D, path: str | Path, *, name: str = "gummy_snake_model") -> Path:
    output = Path(path)
    lines = [f"solid {name}"]
    for mesh in model.meshes:
        for face in mesh.faces:
            if len(face) < 3:
                continue
            first = face[0]
            for index in range(1, len(face) - 1):
                a, b, c = (
                    mesh.vertices[first],
                    mesh.vertices[face[index]],
                    mesh.vertices[face[index + 1]],
                )
                normal = triangle_normal(a, b, c)
                lines.append(f"  facet normal {normal.x:.9g} {normal.y:.9g} {normal.z:.9g}")
                lines.append("    outer loop")
                for vertex in (a, b, c):
                    lines.append(f"      vertex {vertex.x:.9g} {vertex.y:.9g} {vertex.z:.9g}")
                lines.append("    endloop")
                lines.append("  endfacet")
    lines.append(f"endsolid {name}")
    output.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return output
