"""OBJ/STL export helpers for software 3D models."""

from __future__ import annotations

from collections.abc import Iterable
from pathlib import Path
from typing import TextIO

from gummysnake.drawing.renderer3d import Model3D, _model_rust_handle

from .math3d import triangle_normal

_EXPORT_WRITE_CHUNK_LINES = 16384


def _write_chunked(stream: TextIO, lines: Iterable[str]) -> None:
    chunk: list[str] = []
    for line in lines:
        chunk.append(line)
        if len(chunk) >= _EXPORT_WRITE_CHUNK_LINES:
            stream.write("".join(chunk))
            chunk.clear()
    if chunk:
        stream.write("".join(chunk))


def save_obj(model: Model3D, path: str | Path) -> Path:
    output = Path(path)
    handle = _model_rust_handle(model)
    if handle is not None:
        try:
            handle.save_obj(str(output))
        except ValueError as exc:
            from gummysnake.exceptions import ArgumentValidationError

            raise ArgumentValidationError(str(exc)) from exc
        return output

    def lines() -> Iterable[str]:
        yield "# Generated by Gummy Snake\n"
        vertex_offset = 1
        for mesh in model.meshes:
            for vertex in mesh.vertices:
                yield f"v {vertex.x:.9g} {vertex.y:.9g} {vertex.z:.9g}\n"
            for u, v in mesh.texcoords:
                yield f"vt {u:.9g} {v:.9g}\n"
            for face in mesh.faces:
                yield "f " + " ".join(str(index + vertex_offset) for index in face) + "\n"
            vertex_offset += len(mesh.vertices)

    with output.open("w", encoding="utf-8") as stream:
        _write_chunked(stream, lines())
    return output


def save_stl(model: Model3D, path: str | Path, *, name: str = "gummy_snake_model") -> Path:
    output = Path(path)
    handle = _model_rust_handle(model)
    if handle is not None:
        try:
            handle.save_stl(str(output), name=name)
        except ValueError as exc:
            from gummysnake.exceptions import ArgumentValidationError

            raise ArgumentValidationError(str(exc)) from exc
        return output

    def lines() -> Iterable[str]:
        yield f"solid {name}\n"
        for mesh in model.meshes:
            for face in mesh.faces:
                if len(face) < 3:
                    continue
                first = face[0]
                for index in range(1, len(face) - 1):
                    a, b, c = (
                        mesh.vertices[first],
                        mesh.vertices[face[index]],
                        mesh.vertices[face[index + 1]],
                    )
                    normal = triangle_normal(a, b, c)
                    yield f"  facet normal {normal.x:.9g} {normal.y:.9g} {normal.z:.9g}\n"
                    yield "    outer loop\n"
                    for vertex in (a, b, c):
                        yield f"      vertex {vertex.x:.9g} {vertex.y:.9g} {vertex.z:.9g}\n"
                    yield "    endloop\n"
                    yield "  endfacet\n"
        yield f"endsolid {name}\n"

    with output.open("w", encoding="utf-8") as stream:
        _write_chunked(stream, lines())
    return output
