"""Compatibility re-exports for environment, timing, and input API topics."""

from __future__ import annotations

from gummysnake.api.environment import (
    cursor,
    display_height,
    display_width,
    focused,
    no_cursor,
    window_height,
    window_width,
)
from gummysnake.api.input import (
    exit_pointer_lock,
    is_text_input_active,
    key,
    key_code,
    key_is_down,
    key_is_pressed,
    mouse_button,
    mouse_is_inside_window,
    mouse_is_pressed,
    mouse_x,
    mouse_y,
    moved_x,
    moved_y,
    pmouse_x,
    pmouse_y,
    pointer_lock_mode,
    request_pointer_lock,
    start_text_input,
    stop_text_input,
    touches,
)
from gummysnake.api.timing import (
    delta_time,
    frame_count,
    frame_rate,
    get_target_frame_rate,
    is_looping,
    loop,
    millis,
    no_loop,
    redraw,
)

__all__ = [
    "window_width",
    "window_height",
    "display_width",
    "display_height",
    "focused",
    "cursor",
    "no_cursor",
    "mouse_x",
    "mouse_y",
    "pmouse_x",
    "pmouse_y",
    "moved_x",
    "moved_y",
    "mouse_is_pressed",
    "mouse_is_inside_window",
    "mouse_button",
    "key",
    "key_code",
    "key_is_pressed",
    "start_text_input",
    "stop_text_input",
    "is_text_input_active",
    "key_is_down",
    "touches",
    "request_pointer_lock",
    "exit_pointer_lock",
    "pointer_lock_mode",
    "frame_rate",
    "frame_count",
    "delta_time",
    "millis",
    "no_loop",
    "loop",
    "redraw",
    "is_looping",
    "get_target_frame_rate",
]
