"""Compatibility re-exports for media/text/pixel API topics."""

from __future__ import annotations

from gummysnake.api.compositing import (
    blend,
    blend_mode,
    erase,
    no_erase,
)
from gummysnake.api.images import (
    image,
    no_tint,
    tint,
)
from gummysnake.api.pixels import (
    copy,
    filter,
    get,
    load_pixel_bytes,
    load_pixels,
    pixel_array,
    pixels,
    save_canvas,
    save_frames,
    save_gif,
    set,
    update_pixels,
)
from gummysnake.api.text import (
    describe,
    describe_element,
    font_ascent,
    font_bounds,
    font_descent,
    font_width,
    grid_output,
    text,
    text_align,
    text_ascent,
    text_batch,
    text_bounds,
    text_descent,
    text_direction,
    text_font,
    text_leading,
    text_output,
    text_properties,
    text_property,
    text_size,
    text_style,
    text_weight,
    text_width,
    text_widths,
    text_wrap,
)

__all__ = [
    "blend_mode",
    "blend",
    "erase",
    "no_erase",
    "image",
    "tint",
    "no_tint",
    "load_pixels",
    "load_pixel_bytes",
    "pixels",
    "pixel_array",
    "update_pixels",
    "get",
    "set",
    "copy",
    "filter",
    "save_canvas",
    "save_frames",
    "save_gif",
    "text",
    "text_batch",
    "text_size",
    "text_font",
    "text_style",
    "text_align",
    "text_leading",
    "text_width",
    "text_widths",
    "text_ascent",
    "text_descent",
    "font_ascent",
    "font_descent",
    "font_width",
    "font_bounds",
    "text_bounds",
    "text_direction",
    "text_wrap",
    "text_weight",
    "text_property",
    "text_properties",
    "describe",
    "describe_element",
    "text_output",
    "grid_output",
]
