"""Structural protocols for composed canvas renderer mixins."""

from __future__ import annotations

from collections.abc import Callable
from typing import Any, Protocol

from gummysnake.backend.canvas_runtime.renderer.renderer_state.batch_state import (
    ModelBatchKey,
    ModelTransformPayload,
)
from gummysnake.core.state import StyleState
from gummysnake.core.transform import Matrix2D

MatrixPayload = tuple[float, float, float, float, float, float]
PrimitiveBatchRecord = tuple[object, ...]
ImageBatchRecord = tuple[
    object,
    float,
    float,
    float,
    float,
    tuple[int, int, int, int] | None,
    MatrixPayload,
]
TextMetricKey = tuple[str, str | None, int, int]


class CanvasRendererHost(Protocol):
    _skip_canvas_end_frame: bool
    _last_pixel_bytes: bytes | None
    _current_matrix_payload: MatrixPayload
    _clip_depth: int
    physical_width: int
    physical_height: int

    def _flush_line_batch(self) -> None: ...
    def _flush_line_batch_only(self) -> None: ...
    def _flush_primitive_batch_only(self) -> None: ...
    def _flush_image_batch(self) -> None: ...
    def _flush_model_batch(self) -> None: ...
    def _queue_fast_rust_image(
        self,
        rust_image: object,
        dx: float,
        dy: float,
        dw: float,
        dh: float,
        style: dict[str, object],
        matrix: MatrixPayload,
    ) -> None: ...
    def _queue_model_batch(self, key: ModelBatchKey, transform: ModelTransformPayload) -> bool: ...
    def _record_fill_primitive_batch(
        self,
        records: list[tuple[object, ...]],
        transform: Matrix2D,
    ) -> None: ...
    def _queue_primitive_batch(
        self,
        kind: int,
        coords: tuple[float, float, float, float, float, float],
        style: StyleState,
        transform: Matrix2D,
    ) -> bool: ...
    def _flush_text_batch(self, *, final: bool = False) -> None: ...
    def _count(self, name: str, amount: int = 1) -> None: ...
    def _max_count(self, name: str, value: int) -> None: ...
    def _call[T](self, operation: str, callback: Callable[..., T], *args: object) -> T: ...
    def _require_canvas(self) -> Any: ...
    def _require_canvas_method(self, name: str, operation: str) -> Callable[..., Any]: ...
    def _style_payload(self, style: StyleState) -> dict[str, object]: ...
    def _matrix_payload(self, transform: Matrix2D) -> MatrixPayload: ...
    def _can_use_current_state(self, style: StyleState, transform: Matrix2D) -> bool: ...
    def set_current_style(self, style: StyleState) -> None: ...
    def set_current_matrix(self, transform: Matrix2D) -> None: ...
    def remember_current_matrix(self, transform: Matrix2D) -> None: ...
    def push_canvas_state(self) -> None: ...
    def pop_canvas_state(self) -> None: ...
    def translate(self, x: float, y: float) -> None: ...
    def rotate(self, angle: float) -> None: ...
    def scale(self, x: float, y: float | None = None) -> None: ...
    def shear_x(self, angle: float) -> None: ...
    def shear_y(self, angle: float) -> None: ...
    def apply_matrix(self, transform: Matrix2D) -> None: ...
    def reset_matrix(self) -> None: ...
    def polygon(
        self,
        points: list[tuple[float, float]],
        style: StyleState,
        transform: Matrix2D,
        *,
        close: bool = True,
    ) -> None: ...
    def complex_polygon(
        self,
        outer: list[tuple[float, float]],
        contours: list[list[tuple[float, float]]],
        style: StyleState,
        transform: Matrix2D,
        *,
        close: bool = True,
    ) -> None: ...
    def begin_clip(
        self,
        outer: list[tuple[float, float]],
        contours: list[list[tuple[float, float]]],
        transform: Matrix2D,
    ) -> None: ...
    def end_clip(self) -> None: ...
    def _cached_text_metric(
        self,
        key: TextMetricKey,
        operation: str,
        callback: Callable[..., Any],
        *args: object,
    ) -> float: ...
