"""Structural protocols for composed canvas renderer mixins."""

from __future__ import annotations

from collections.abc import Callable
from typing import Any, Protocol

from gummysnake.core.state import StyleState
from gummysnake.core.transform import Matrix2D

MatrixPayload = tuple[float, float, float, float, float, float]
PrimitiveBatchRecord = tuple[object, ...]
ImageBatchRecord = tuple[
    object,
    float,
    float,
    float,
    float,
    tuple[int, int, int, int] | None,
    MatrixPayload,
]
TextMetricKey = tuple[str, str | None, int, int]


class CanvasRendererHost(Protocol):
    _line_batch: list[tuple[float, float, float, float]]
    _line_batch_style: dict[str, object] | None
    _line_batch_matrix: MatrixPayload | None
    _line_batch_current: bool
    _primitive_batch: list[PrimitiveBatchRecord]
    _primitive_batch_style: dict[str, object] | None
    _primitive_batch_matrix: MatrixPayload | None
    _primitive_batch_current: bool
    _primitive_batch_mode: str | None
    _text_batch: list[tuple[str, float, float]]
    _text_batch_style: dict[str, object] | None
    _text_batch_matrix: MatrixPayload | None
    _image_batch: list[ImageBatchRecord]
    _image_batch_style: dict[str, object] | None
    _image_batch_matrix: MatrixPayload | None
    _skip_canvas_end_frame: bool
    _last_pixel_bytes: bytes | None
    _current_matrix_payload: MatrixPayload
    _clip_depth: int
    physical_width: int
    physical_height: int

    def _flush_line_batch(self) -> None: ...
    def _flush_line_batch_only(self) -> None: ...
    def _flush_primitive_batch_only(self) -> None: ...
    def _flush_image_batch(self) -> None: ...
    def _flush_text_batch(self, *, final: bool = False) -> None: ...
    def _count(self, name: str, amount: int = 1) -> None: ...
    def _max_count(self, name: str, value: int) -> None: ...
    def _call[T](self, operation: str, callback: Callable[..., T], *args: object) -> T: ...
    def _require_canvas(self) -> Any: ...
    def _require_canvas_method(self, name: str, operation: str) -> Callable[..., Any]: ...
    def _style_payload(self, style: StyleState) -> dict[str, object]: ...
    def _matrix_payload(self, transform: Matrix2D) -> MatrixPayload: ...
    def _can_use_current_state(self, style: StyleState, transform: Matrix2D) -> bool: ...
    def set_current_style(self, style: StyleState) -> None: ...
    def set_current_matrix(self, transform: Matrix2D) -> None: ...
    def remember_current_matrix(self, transform: Matrix2D) -> None: ...
    def push_canvas_state(self) -> None: ...
    def pop_canvas_state(self) -> None: ...
    def translate(self, x: float, y: float) -> None: ...
    def rotate(self, angle: float) -> None: ...
    def scale(self, x: float, y: float | None = None) -> None: ...
    def shear_x(self, angle: float) -> None: ...
    def shear_y(self, angle: float) -> None: ...
    def apply_matrix(self, transform: Matrix2D) -> None: ...
    def reset_matrix(self) -> None: ...
    def end_clip(self) -> None: ...
    def _cached_text_metric(
        self,
        key: TextMetricKey,
        operation: str,
        callback: Callable[..., Any],
        *args: object,
    ) -> float: ...
