"""Pythonic ECS API for Gummy Snake."""

from __future__ import annotations

from gummysnake.ecs import canvas, spatial, types
from gummysnake.ecs.logical_plan.actions import (
    Action,
    DefaultAction,
    ForEachAction,
    RuntimeUdfDefinition,
    SystemPlan,
    UdfDefinition,
    UdfIterableDefinition,
    UdfPlanDefinition,
    WhenAction,
    conditional,
    do,
    do_in_order,
    do_in_parallel,
    emit_event,
    for_each,
    otherwise,
    set,
    udf,
    udf_plan,
    when,
)
from gummysnake.ecs.logical_plan.expressions import (
    ComponentExpressionProxy,
    Expression,
    QueryProxy,
    Vector,
    all_of,
    any_of,
    dt,
    exists,
    key_is_down,
    literal,
)
from gummysnake.ecs.logical_plan.specifications import (
    Added,
    Changed,
    EventReader,
    EventWriter,
    Query,
    Removed,
    Res,
    ResMut,
    Tag,
    Without,
)
from gummysnake.ecs.logical_plan.systems import (
    RuntimeSystemDefinition,
    SystemDefinition,
    SystemPlanDefinition,
    system,
    system_plan,
)
from gummysnake.ecs.world_facade import Entity, EntityMutation, EntityView, SystemHandle

__all__ = [
    "Action",
    "Added",
    "Changed",
    "ComponentExpressionProxy",
    "DefaultAction",
    "Entity",
    "EntityMutation",
    "EntityView",
    "EventReader",
    "EventWriter",
    "Expression",
    "ForEachAction",
    "Query",
    "QueryProxy",
    "Removed",
    "Res",
    "ResMut",
    "RuntimeSystemDefinition",
    "RuntimeUdfDefinition",
    "SystemDefinition",
    "SystemHandle",
    "SystemPlan",
    "SystemPlanDefinition",
    "Tag",
    "UdfDefinition",
    "UdfIterableDefinition",
    "UdfPlanDefinition",
    "Vector",
    "WhenAction",
    "Without",
    "all_of",
    "any_of",
    "canvas",
    "conditional",
    "do",
    "do_in_order",
    "do_in_parallel",
    "dt",
    "emit_event",
    "exists",
    "for_each",
    "key_is_down",
    "literal",
    "otherwise",
    "set",
    "spatial",
    "system",
    "system_plan",
    "types",
    "udf",
    "udf_plan",
    "when",
]
