"""Compatibility module for logical-plan structural action builders."""

from __future__ import annotations

from gummysnake.ecs.logical_plan.actions import (
    Action,
    DefaultAction,
    EntityIteratorSource,
    EventIterableSource,
    ExpressionIterableSource,
    ForEachAction,
    IterableSource,
    RuntimeUdfDefinition,
    SystemPlan,
    UdfCallExpression,
    UdfDefinition,
    UdfIterableDefinition,
    UdfPlanDefinition,
    WhenAction,
    action_query_refs,
    action_write_targets,
    add_component_action,
    add_tag_action,
    despawn_action,
    emit_event,
    remove_component_action,
    remove_tag_action,
    set,
    udf,
    udf_plan,
    validate_mutation_metadata,
)
from gummysnake.ecs.logical_plan.building import (
    active_build_session,
    append_action,
    build_session,
    conditional,
    do,
    do_in_order,
    do_in_parallel,
    for_each,
    otherwise,
    when,
)

__all__ = [
    "Action",
    "DefaultAction",
    "EntityIteratorSource",
    "EventIterableSource",
    "ExpressionIterableSource",
    "ForEachAction",
    "IterableSource",
    "RuntimeUdfDefinition",
    "SystemPlan",
    "UdfCallExpression",
    "UdfDefinition",
    "UdfIterableDefinition",
    "UdfPlanDefinition",
    "WhenAction",
    "action_query_refs",
    "action_write_targets",
    "active_build_session",
    "add_component_action",
    "add_tag_action",
    "append_action",
    "build_session",
    "conditional",
    "despawn_action",
    "do",
    "do_in_order",
    "do_in_parallel",
    "emit_event",
    "for_each",
    "otherwise",
    "remove_component_action",
    "remove_tag_action",
    "set",
    "udf",
    "udf_plan",
    "validate_mutation_metadata",
    "when",
]
