"""Action nodes, structural commands, and UDF declarations for logical ECS plans."""

from __future__ import annotations

from .nodes import (
    Action,
    DefaultAction,
    EntityIteratorSource,
    EventIterableSource,
    ExpressionIterableSource,
    ForEachAction,
    IterableSource,
    LoopItem,
    SystemPlan,
    UdfArgument,
    UdfDefinition,
    UdfIterableSource,
    UdfPlanDefinition,
    WhenAction,
    _RuntimeUdfBase,
)
from .structural import (
    action_query_refs,
    action_write_targets,
    add_component_action,
    add_tag_action,
    despawn_action,
    emit_event,
    remove_component_action,
    remove_tag_action,
    set,
)
from .udf import (
    RuntimeUdfDefinition,
    UdfCallExpression,
    UdfIterableDefinition,
    udf,
    udf_plan,
    validate_mutation_metadata,
)

__all__ = [
    "Action",
    "DefaultAction",
    "EntityIteratorSource",
    "EventIterableSource",
    "ExpressionIterableSource",
    "ForEachAction",
    "IterableSource",
    "LoopItem",
    "RuntimeUdfDefinition",
    "SystemPlan",
    "UdfArgument",
    "UdfCallExpression",
    "UdfDefinition",
    "UdfIterableDefinition",
    "UdfIterableSource",
    "UdfPlanDefinition",
    "WhenAction",
    "_RuntimeUdfBase",
    "action_query_refs",
    "action_write_targets",
    "add_component_action",
    "add_tag_action",
    "despawn_action",
    "emit_event",
    "remove_component_action",
    "remove_tag_action",
    "set",
    "udf",
    "udf_plan",
    "validate_mutation_metadata",
]
