from pathlib import Path

import pytest

import gummysnake as gs
from gummysnake.assets.model import load_model
from gummysnake.drawing.renderer3d import _model_rust_handle
from gummysnake.drawing.software3d import save_obj, save_stl


def test_load_model_supports_local_obj_with_negative_indices(tmp_path: Path):
    obj_path = tmp_path / "triangle.obj"
    obj_path.write_text(
        "\n".join(
            [
                "v 0 0 0",
                "v 2 0 0",
                "v 0 1 0",
                "f -3 -2 -1",
            ]
        ),
        encoding="utf-8",
    )

    model = gs.load_model(obj_path)

    assert len(model.meshes) == 1
    mesh = model.meshes[0]
    assert len(mesh.vertices) == 3
    assert mesh.faces == ((0, 1, 2),)
    assert model.source == obj_path


def test_load_model_uses_rust_handle_for_export_without_materializing_meshes(tmp_path: Path):
    obj_path = tmp_path / "triangle.obj"
    obj_path.write_text("v 0 0 0\nv 1 0 0\nv 0 1 0\nf 1 2 3\n", encoding="utf-8")

    model = load_model(obj_path)
    handle = _model_rust_handle(model)
    if handle is None:
        pytest.skip("canvas runtime does not expose Rust-owned model handles")

    assert model._meshes is None
    assert handle.vertex_count() == 3
    assert handle.face_count() == 1

    obj_output = save_obj(model, tmp_path / "out.obj")
    stl_output = save_stl(model, tmp_path / "out.stl", name="demo")

    assert model._meshes is None
    assert obj_output.read_text(encoding="utf-8").splitlines() == [
        "# Generated by Gummy Snake",
        "v 0 0 0",
        "v 1 0 0",
        "v 0 1 0",
        "f 1 2 3",
    ]
    assert stl_output.read_text(encoding="utf-8").splitlines() == [
        "solid demo",
        "  facet normal 0 0 1",
        "    outer loop",
        "      vertex 0 0 0",
        "      vertex 1 0 0",
        "      vertex 0 1 0",
        "    endloop",
        "  endfacet",
        "endsolid demo",
    ]


def test_load_model_preserves_rust_handle_and_materializes_meshes_lazily(tmp_path, monkeypatch):
    obj_path = tmp_path / "triangle.obj"
    obj_path.write_text("v 0 0 0\nv 1 0 0\nv 0 1 0\nf 1 2 3\n", encoding="utf-8")

    class MeshHandle:
        def __init__(self, owner):
            self._owner = owner

        def to_mesh_payload(self):
            return self._owner.to_mesh_payload()

    class Handle:
        def __init__(self):
            self.materialized = 0
            self.saved_obj: str | None = None
            self.saved_stl: tuple[str, str] | None = None

        def to_mesh_handle(self):
            return MeshHandle(self)

        def to_mesh_payload(self):
            self.materialized += 1
            return {
                "vertices": [(0.0, 0.0, 0.0), (1.0, 0.0, 0.0), (0.0, 1.0, 0.0)],
                "faces": [[0, 1, 2]],
                "texcoords": [],
                "normals": [],
            }

        def save_obj(self, path):
            self.saved_obj = path
            Path(path).write_text("# rust obj\n", encoding="utf-8")

        def save_stl(self, path, *, name="gummy_snake_model"):
            self.saved_stl = (path, name)
            Path(path).write_text(f"solid {name}\nendsolid {name}\n", encoding="utf-8")

    handle = Handle()

    class Runtime:
        def parse_obj_model_handle(self, text, source, normalize):
            return handle

    monkeypatch.setattr("gummysnake.rust.canvas.require_canvas_runtime", lambda: Runtime())

    model = load_model(obj_path)

    assert _model_rust_handle(model) is handle
    assert handle.materialized == 0
    assert len(model.meshes[0].vertices) == 3
    assert handle.materialized == 1
    assert len(model.meshes[0].vertices) == 3
    assert handle.materialized == 1

    obj_output = save_obj(model, tmp_path / "out.obj")
    stl_output = save_stl(model, tmp_path / "out.stl", name="demo")

    assert handle.saved_obj == str(obj_output)
    assert handle.saved_stl == (str(stl_output), "demo")


def test_load_model_supports_package_resources_and_normalize():
    model = gs.load_model("triangle.obj", normalize=True, package="gummysnake.testing.resources")

    mesh = model.meshes[0]
    xs = [vertex.x for vertex in mesh.vertices]
    ys = [vertex.y for vertex in mesh.vertices]
    zs = [vertex.z for vertex in mesh.vertices]

    assert max(xs) <= 1.0
    assert min(xs) >= -1.0
    assert max(ys) <= 1.0
    assert min(ys) >= -1.0
    assert max(zs) == 0.0
    assert min(zs) == 0.0
